#!/bin/bash
set -e

export ANYENV_ROOT="$HOME/.anyenv"

if [[ -z `anyenv envs` ]]; then
  echo -ne '\n' | anyenv install --init
else
  echo "Already initialized anyenv"
fi

echo "Initializing anyenvs..."
make init.envs

echo "Initializing python3..."
`$ANYENV_ROOT/envs/pyenv/bin/pyenv rehash`
if [[ -z `pyenv version | grep 3.7.4` ]]; then
  echo -ne '\n' | pyenv install 3.7.4
else
  echo "already python3 exists."
fi

pyenv global 3.7.4
pyenv rehash

echo "Initializing nvim..."
make init.vim

echo "Initializing tmux..."
make init.tmux

echo "Deployment binaries..."
make deploy.bin

echo "Completed."

