#!/bin/bash
set -eu

. "$DOTPATH/lib/utilities.sh"

bin_deploy() {
  local binary_name="$1"
  if [[ ! -e "$HOME/bin/$binary_name" ]]; then
    if [[ ! -e "$HOME/bin" ]]; then
      mkdir -p "$HOME/bin"
    fi
    log_info "Not linking $binary_name ."
    ln -s "$DOTPATH/bin/$binary_name" "$HOME/bin/$binary_name"
    log_pass "Deploy completed $binary_name symbolic link."
  else
    log_warn "Already deployed $binary_name..."
  fi
}

bin_deploy "gcp-context"
bin_deploy "kube-context"
bin_deploy "wifi-info"
