#!/bin/bash
set -e
. "$DOTPATH/lib/utilities.sh"

pip install -U neovim
if [[ ! -e "$XDG_CONFIG_HOME/nvim" ]]; then
  log_info "path $DOTPATH/nvim/ to $XDG_CONFIG_HOME/nvim ."
  ln -s "$DOTPATH/nvim/" "$XDG_CONFIG_HOME/nvim"
  log_pass "linked nvim config directory"
else
  log_warn "already linked nvim config directory."
fi
