#!/bin/bash
set -e
. "$DOTPATH/lib/utilities.sh"

if [[ ! -e "$HOME/.tmux.conf" ]]; then
  log_info "path $DOTPATH/.tmux.conf to $HOME/.tmux.conf ."
  ln -s "$DOTPATH/.tmux.conf" "$HOME/.tmux.conf"
  log_pass "linked tmux config directory"
else
  log_warn "already linked tmux config directory."
fi
